INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'JPMorgan Chase', 'New York City', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'Bank of America', 'Charlotte', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'Citigroup', 'New York City', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'Wells Fargo', 'San Francisco', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'Goldman Sachs', 'New York City', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'Morgan Stanley', 'New York City', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'U.S. Bancorp', 'Minneapolis', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'PNC Financial Services', 'Pittsburgh', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'Truist Financial', 'Charlotte', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'TD Bank, N.A.', 'Cherry Hill, New Jersey', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'Charles Schwab Corporation', 'Westlake, Texas', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'Capital One', 'McLean, Virginia', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'The Bank of New York Mellon', 'New York City', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'State Street Corporation', 'Boston', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'BMO USA', 'Chicago', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'American Express', 'New York City', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'HSBC Bank USA', 'New York City', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'Citizens Financial Group', 'Providence, Rhode Island', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'First Citizens BancShares', 'Raleigh, North Carolina', 'http://example.com/logo.png');
INSERT INTO organization ("type", "name", "address", "logoUrl") VALUES ('BANK', 'M&T Bank', 'Buffalo, New York', 'http://example.com/logo.png');
